# Generated by Django 3.0.5 on 2020-05-27 12:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hostel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.CharField(blank=True, max_length=12)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('course', models.CharField(choices=[('BE', 'BE'), ('B.Tech', 'B.Tech'), ('M.Tech', 'M.Tech'), ('B. Pharma', 'B. Pharma'), ('MBA', 'MBA'), ('CA', 'CA')], max_length=20, null=True)),
                ('permanent_address', models.TextField(blank=True, null=True)),
                ('temporary_address', models.TextField(blank=True)),
                ('allotted', models.BooleanField(default=False)),
                ('apply', models.BooleanField(default=False)),
                ('room_allocation_date', models.DateField(blank=True, null=True)),
                ('contact_no', models.CharField(blank=True, max_length=13, null=True, unique=True)),
                ('parent_no', models.CharField(blank=True, max_length=13, null=True, unique=True)),
                ('profile_pic', models.FileField(blank=True, upload_to='profile_picture/', verbose_name='profile_pic')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hostel.Room')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Student_Profile',
            },
        ),
    ]
