# Generated by Django 3.0.5 on 2020-05-28 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='billing_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='duration',
            field=models.CharField(choices=[('Quarterly', '3'), ('Half Yearly', '6'), ('Yearly', '12')], default='12', max_length=20),
            preserve_default=False,
        ),
    ]
