# Generated by Django 3.0.5 on 2020-05-28 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200528_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='payment_request',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='payment_status',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='duration',
            field=models.CharField(choices=[('3', 'Quarterly'), ('6', 'Half Yearly'), ('12', 'Yearly')], default=3, max_length=20),
        ),
    ]
