# Generated by Django 3.0.5 on 2020-05-30 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200528_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='payment_request_date',
            field=models.DateField(null=True),
        ),
    ]
